splitter: sentence_text_splitter_LC #token_text_splitter #sentence_text_splitter #token_text_splitter #sentence_text_splitter_LC  #semantic_splitter
  # splitter: token_text_splitter #sentence_text_splitter #token_text_splitter #sentence_text_splitter_LC  #semantic_splitter
metadata:
  - default
reader:
  - sharepointreader

mode: update #update
  #mode: update
adjacent_chunks: true

sentence_text_splitter_LC:
  chunk_size: 256
  chunk_overlap: 0

token_text_splitter:
  chunk_size: 256
  chunk_overlap: 0

embedding_type: ""
embedding_url: "https://a2f54faa9c79745f795eea54ae09d029-f4695fd2fc8f6c01.elb.us-east-1.amazonaws.com/deployment/published/bgenew/v1/"
embedding_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic2hhcm1pc3RoYS1jaG91ZGh1cnkiLCJ0eXBlIjoiYXBpIiwiaWQiOiIvZGVwbG95bWVudC9iZ2VuZXcvIn0.RaI29I7-Kddxr47GRu-DffBkEIGDH825JE-M2QVzx3E"
batch_size: 32

mlflow:
  experiment: ingestion_sharepoint

sharepointreader:
  - inputs:
      loader_args:
        client_id: "f9678800-d2e6-46e6-8a40-6b0375e29c28"
        client_secret: "{{ client_secret }}"
        tenant_id: "069efc93-08c9-47d0-9324-da87e29a605d"
        # for sharepoint sharepoint_site and sharepoint_site_path is needed.
        sharepoint_site: "1convergence.sharepoint.com"
        sharepoint_site_path: "testsharepoint"
        access_token: "{{ access_token }}"
        #access_token: "eyJ0eXAiOiJKV1QiLCJub25jZSI6Il9OeDJCNTdEWGgxTHlZRzVTeXNSMlVvNWk4Z2NwcVR2YlViUDYyeTJ6ZGsiLCJhbGciOiJSUzI1NiIsIng1dCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSIsImtpZCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wNjllZmM5My0wOGM5LTQ3ZDAtOTMyNC1kYTg3ZTI5YTYwNWQvIiwiaWF0IjoxNzQ2NTA4MzM2LCJuYmYiOjE3NDY1MDgzMzYsImV4cCI6MTc0NjU5NTAzNiwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsicDEiXSwiYWlvIjoiQVdRQW0vOFpBQUFBS2daT0lHUWpBZVVpR3R1eDcvTWxwUnlJRFhQN2NOY0hCU21VR1RtMmRUOG5STVR6bTQ2ZmlaZmZWK2tMNnF2WWNQczNCY3YzQnNpKzk0SUcvMDROaXk4cTlLc3hDcFR0VG5XYks5d3RENXpieXpsN092cTl5OEVseTNsbUp3RDAiLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IlZpamFwdXJlIiwiZ2l2ZW5fbmFtZSI6IktpcmFuIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTAzLjQ5LjI1Mi4xNTgiLCJuYW1lIjoiS2lyYW4gVmlqYXB1cmUiLCJvaWQiOiI4Y2Q2N2RkZi00YmZlLTQxOTktODNlMS1mZTI0ODBiMmM0ODgiLCJwbGF0ZiI6IjgiLCJwdWlkIjoiMTAwMzIwMDQ3Q0JFNTQyMiIsInJoIjoiMS5BUzRBa195ZUJza0kwRWVUSk5xSDRwcGdYUU1BQUFBQUFBQUF3QUFBQUFBQUFBQzVBSmN1QUEuIiwic2NwIjoiQVBJQ29ubmVjdG9ycy5SZWFkLkFsbCBBUElDb25uZWN0b3JzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZC5BbGwgRmlsZXMuUmVhZC5TZWxlY3RlZCBOb3Rlcy5DcmVhdGUgTm90ZXMuUmVhZCBOb3Rlcy5SZWFkLkFsbCBOb3Rlcy5SZWFkV3JpdGUuQWxsIG9wZW5pZCBwcm9maWxlIFNpdGVzLlJlYWQuQWxsIFNpdGVzLlNlbGVjdGVkIFVzZXIuUmVhZCBlbWFpbCIsInNpZCI6IjAwM2UyMjU5LTkwNjUtYTZiMi1kZmVhLWY3ZDBlYjY3YzJmMCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IklhaXV6OW1sVnNnOVNnRUNyOE9QRU5KTVd5VTF4S3l2ODIzSXZPOW9WeDQiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiIwNjllZmM5My0wOGM5LTQ3ZDAtOTMyNC1kYTg3ZTI5YTYwNWQiLCJ1bmlxdWVfbmFtZSI6ImtpcmFuQGRrdWJlLmlvIiwidXBuIjoia2lyYW5AZGt1YmUuaW8iLCJ1dGkiOiJnZnhOdkpQeEZFaUgzTkV5c1BRaEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJmMjhhMWY1MC1mNmU3LTQ1NzEtODE4Yi02YTEyZjJhZjZiNmMiLCIxYTdkNzhiNi00MjlmLTQ3NmItYjhlYi0zNWZiNzE1ZmZmZDQiLCIwNTI2NzE2Yi0xMTNkLTRjMTUtYjJjOC02OGUzYzIyYjlmODAiLCIxNzA3MTI1ZS0wYWEyLTRkNGQtODY1NS1hN2M3ODZjNzZhMjUiLCJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2NjIjpbIkNQMSJdLCJ4bXNfZnRkIjoidjJBSkw5Wm5SN0hQejh5czZrdTRNcDVHSHp3dWxWOUZmVlZkYllEQmhmd0JkWE51YjNKMGFDMWtjMjF6IiwieG1zX2lkcmVsIjoiMSAxMCIsInhtc19zc20iOiIxIiwieG1zX3N0Ijp7InN1YiI6ImJzdERjb0NVaGN4YWpZU2V6WTNweUlGS2FvS3dCaFloeF9GRkVGd0k3dk0ifSwieG1zX3RjZHQiOjE1ODA4NDk2MDZ9.hmjD_CNVAWTq8EP30lhg1_9mWxp7KBYQZ8x922cr6fxM3sCFrj4WDdLyR3Ui4nm85tUwy9kloL-WHn7my8wuZCl11VCubWnLnvKTjnZzpzJENRptMSuNn26qkZqOVYBMwWvXG3QbH_mXpnvdUrkDuUF8V2iOuqQ8Q1mSpM1rTTM6kuaAYhx27sG7U9l4vO8WaYyzl-y00RiU5whHhJWqcMihAxIV_18nQGaWGXlJhzYf8SmPbd_NmMR8C4yvC1bNP8_kYYqxBcVli5NMDZfhb0DMhWjE9Ly1jLvntb7-jPHwtr0BSlBC9VEPHCK76cM_DF6t1uDG1Qfy_OTqcvJ9Pg"
      data_args:
        #sharepoint_folder_path: ""     #for single file/folder
        sharepoint_folder_path: null                   # for all files in sharepoint
        # doc_source: ""
        # state_category: ""
        # designation_category: ""
        # topic_category: ""
        recursive: true

