splitter: sentence_text_splitter_LC #token_text_splitter #sentence_text_splitter #token_text_splitter #sentence_text_splitter_LC  #semantic_splitter
  # splitter: token_text_splitter #sentence_text_splitter #token_text_splitter #sentence_text_splitter_LC  #semantic_splitter
metadata:
  - default
reader:
  - filereader
  #- githubreader
  #- confluencereader
  #- sharepointreader

mode: sync #update
  #mode: update
adjacent_chunks: true

sentence_text_splitter_LC:
  chunk_size: 256
  chunk_overlap: 0

token_text_splitter:
  chunk_size: 256
  chunk_overlap: 0

embedding_type: "" #optional
embedding_url: ""   # custom embedding model url
embedding_key: ""  # custom embedding model serving token
batch_size: 32

sky:
  batch_size: 32

mlflow:
  # experiment: nv-trial
  experiment: embedding

filereader:
  - inputs:
      loader_args:
        input_dir: /home/sharmistha-choudhury/configs/Contracts
        recursive: true 
        exclude_hidden: true 
        raise_on_error: true




